<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\InfraccionTransito;

class InfraccionesTransitoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $infracciones = [
            ['2', '', 'Desobediencia a las disposiciones (d.539)', 1.5],
            ['3', '', 'Desobediencia a señalización (d.540)', 1.5],
            ['4', 'B', 'Vehículo circulando por la acera (d.541)', 4.0],
            ['4', '4/2', 'Conduce usando celular. (D.677, inc. L). Decreto Nº 81/014 de 03/04/2014 artículo 58', 3.0, 'Decreto Nº 81/014 de 03/04/2014'],
            ['4', '9/1', 'Menor en asiento delantero. Decreto Nº 81/014 de 03/04/2014 artículo 1 (D.677.1)', 3.0, 'Decreto Nº 81/014 de 03/04/2014'],
            ['4', '9/2', 'No utiliza sistema de retención infantil. Decreto Nº 81/014 de 03/04/2014 artículo 3 (D.677.1)', 2.0, 'Decreto Nº 81/014 de 03/04/2014'],
            ['5', 'A', 'Vehículos: uso indebido de las aceras, no dar preferencia al peatón (d.542)', 4.0],
            ['5', 'B', 'Entrada y salida del inmueble cuando el cordón no está dispuesto a esos efectos (d.542)', 4.0],
            ['5', 'C', 'Prohibición de estacionar sobre la acera (d.542)', 4.0],
            ['5', 'D', 'Circula por ciclovía o bicisenda', 4.0],
            ['6', '', 'Peatón uso indebido de la calzada (d.543)', 0.1],
            ['7', '', 'No obedecer limitaciones de circulación temporaria (d.544)', 1.0],
            ['8', '1', 'Conduce sin licencia o con licencia suspendida (d.545)', 8.0],
            ['8', '2', 'Licencia no habilitada para el vehículo que conduce (d.545)', 2.5],
            ['9', '1', 'Conduce sin poseer cualidades físicas o psíquicas que lo habiliten (d.546)', 2.5],
            ['9', '2', 'Persona con discapacidad conduciendo vehículo sin autorización (d.546)', 2.5],
            ['11', '1', 'Aspirante a conductor no autorizado (d.548)', 1.0],
            ['11', '2', 'Instructor no habilitado (d.548)', 1.0],
            ['12', '15A', 'Alcoholemia', 15.0],
            ['12', '15B', 'Presencia de drogas psicotrópicas', 15.0],
            ['14', '', 'Conduce vehículos especiales sin permiso (d.551)', 2.5],
            ['15', '', 'Conduce con licencia sin reválida (d.552)', 2.5],
            ['16', '', 'Omisión de actualización de domicilio (d.553)', 0.3],
            ['17', '', 'Posee más de una licencia de conducir (d.554)', 2.5],
            ['18', '', 'Omisión de entregar licencia anterior al recibir una nueva (d.555)', 2.5],
            ['19', '', 'Conduce con licencia vencida (d.556)', 1.0],
            ['21', '', 'Licencia condicional vencida (d.558)', 2.5],
            ['21', '7', 'Niños y adolescentes deberán alcanzar los posapies para poder ser transportados en ciclomotor, motos o similares. (D.698). Decreto Nº 81/014 de 03/04/2014, artículo 2', 1.0, 'Decreto Nº 81/014 de 03/04/2014'],
            ['21', '8', 'No usa chaleco o bandas retro reflectivas reglamentarias o no visible por elemento. (D.709.1) Decreto Nº 81/014 de 03/04/2014, artículos 26,31', 0.5, 'Decreto Nº 81/014 de 03/04/2014'],
            ['22', '', 'Circulación de vehículo sin empadronar (d.559)', 2.5],
            ['22', '4', 'Prohibido el transporte de personas en la caja de vehículos y acoplados. Decreto Nº 81/014 de 03/04/2014 artículo 59', 4.0, 'Decreto Nº 81/014 de 03/04/2014'],
            ['28', '', 'Circula con vehículo no inspeccionado (d.565)', 1.0],
            ['30', '', 'Vehículo circulando con un peso que produzca exceso de presión sobre el pavimento (d.567)', 5.0],
            ['33', '', 'Omisión de comunicar fallecimiento del propietario de un vehículo (d.570)', 0.3],
            ['34', '', 'Circula sin placas de matrícula (d.571)', 1.0],
            ['35', '', 'Circula con placas deterioradas o ubicadas en lugar no visible (d.572)', 1.0],
            ['36', '', 'Circula sin matrícula por extravío- sustracción o deterioro (d.573)', 1.0],
            ['37', '', 'Circula con matrículas no vigentes (d.574)', 1.0],
            ['39', '', 'Circula con placas no originales (d.576)', 1.0],
            ['40', '', 'Mal uso de placas de prueba (d.577)', 1.5],
            ['41', '', 'Circula con placas de prueba de otro departamento sin el permiso correspondiente (d.578)', 1.5],
            ['43', '', 'Mal uso de placas de demostración de usado y de prueba (d.580)', 1.5],
            ['44', '', 'No realiza transferencia (d.581)', 1.0],
            ['47', '', 'Omisión de devolver placas de matrículas beneficiarias de privilegios (d.584)', 1.0],
            ['60', '', 'Obligación de evitar accidentes ante inobservancia de peatones- especialmente de niños o personas con discapacidad (d.597)', 1.5],
            ['61', '', 'No circula por derecha. adelanta en una intersección o adelanta varios vehículos a la vez (d.598)', 1.0],
            ['62', '', 'No conserva la derecha cuando se circula a velocidad reducida (d.599)', 1.0],
            ['63', '', 'No conserva la derecha en rebase de vehículos con sentidos opuestos o no cede el paso a quien circula por la mitad más transitada (d.600)', 1.0],
            ['64', '', 'Circula por izquierda de la calzada con visual limitada (curvas- puentes- declives) (d.601)', 1.0],
            ['65', '', 'Circula en sentido contrario (d.602)', 1.0],
            ['66', '', 'No circular por la derecha alrededor del "rond point" (d.603)', 1.0],
            ['67', '', 'No se mantiene dentro de una senda o abandona con riesgo carriles de circulación (d.604)', 1.0],
            ['68', '', 'Circular por la mitad izquierda en calzadas de doble mano que dispongan de cuatro o más sendas de circulación (d. 605)', 1.0],
            ['69', '', 'No ceder el paso a vehículo que circula en sentido contrario al enfrentar obstáculo (d.606)', 1.0],
            ['70', 'A', 'Adelantar por derecha (d.607)', 0.6],
            ['70', 'B', 'Retomar la línea de marcha antes de encontrarse a distancia segura del rebasado (d.607)', 0.6],
            ['70', 'C', 'Aumentar la velocidad mientras otro vehículo está adelantando (d.607)', 0.6],
            ['70', 'D', 'Adelantar en intersección (d.607)', 0.6],
            ['70', 'E', 'Adelantar por izquierda a quien gira a la izquierda (d.607)', 0.6],
            ['71', '', 'Adelantar cuando otro vehículo inicia igual maniobra (d.608)', 0.6],
            ['72', '', 'Adelantar o rebasar obstáculos en calles de doble sentido invadiendo senda izquierda con riesgo para peatones o vehículos (d.610)', 0.6],
            ['73', '', 'Rebasar vehículo que disminuye la velocidad o se detiene en cruce peatonal- o no detenerse junto a ómnibus detenido en la parada adelantándolo sin precaución (d.610)', 0.6],
            ['75', '', 'No respetar prohibición de adelantamientos (d.612)', 1.0],
            ['76', '', 'No conservar una distancia razonable y prudente en la circulación (d.613)', 1.5],
            ['77', '', 'Seguir vehículos de emergencia a menos de 100 metros (d.614)', 1.5],
            ['78', '', 'Circulación de vehículos especiales o con cargas excesivas, desagradables o peligrosas sin autorización (d.615)', 1.0],
            ['79', '', 'Conducir un vehículo cuando está cargado de tal modo por bultos o personas que se obstaculiza la buena visión del conductor o que estorba el control del vehículo (d.616)', 1.0],
            ['80', '', 'Prohibición de remolcar vehículos (d.617)', 1.0],
            ['81', '', 'Marcha atrás innecesaria (d.618)', 0.5],
            ['82', '', 'En pendientes descendentes no controlar la velocidad con motor (d.619)', 1.5],
            ['85', 'A', 'No respetar cartel de pare (d.622)', 3.0],
            ['85', 'B', 'No respetar cartel de ceda el paso (d.622)', 3.0],
            ['87', '1', 'No ceder el paso al vehículo que aparece por la derecha (d.624)', 1.0],
            ['87', '2', 'No reducir la velocidad en intersecciones de calles no preferenciales (d.624)', 1.0],
            ['88', '', 'Desobediencia al funcionario que dirige tránsito (d.625)', 5.0],
            ['89', 'A', 'Vehículo que cambia de dirección o sentido de marcha no da preferencia (d.626)', 1.0],
            ['89', 'B', 'Vehículo que cambia de frente para salir de inmueble no da preferencia (d.626)', 1.0],
            ['90', '', 'No dar preferencia a peatones (d.627)', 1.0],
            ['92', '', 'No dar preferencia a peatones que transiten por la acera - al entrar o salir de pasaje- edificio o calzada particular (d.629)', 1.0],
            ['93', '', 'No ceder el paso o no ubicarse a la derecha de la calzada ante el pasaje de vehículo autorizado de emergencia usando señales reglamentarias (d.630)', 2.5],
            ['94', '', 'No ubicarse correctamente para girar a la derecha o girar en doble fila a la derecha (d.631)', 1.0],
            ['95', '', 'No ubicarse correctamente para girar a la izquierda o girar en doble fila a la izquierda (d.632)', 1.0],
            ['96', '', 'Salir o ingresar de garaje o pasaje privado por izquierda en calles de doble sentido de circulación (d.633)', 1.0],
            ['97', '', 'Cambio de frente prohibido (d.634)', 1.0],
            ['98', '', 'Giro en lugar prohibido (d.635)', 1.0],
            ['99', '', 'Desplazar vehículo fuera de su curso recto sin seguridad o sin realizar las señales correspondientes en maniobra de giro (d.636)', 1.0],
            ['100', '', 'No realizar señales adecuadas para reducir la marcha o detenerse (d.637)', 0.6],
            ['101', 'A', 'No indicar giro a la izquierda (d.638)', 1.0],
            ['101', 'B', 'No indicar giro a la derecha (d.638)', 1.0],
            ['101', 'C', 'No indicar reducción de velocidad (d.638)', 0.6],
            ['102', '', 'Hacer señales de giro o detención y no realizar maniobra (d.639)', 0.6],
            ['103', '1', 'Imprudencia o desatención en el manejo (d.640)', 1.5],
            ['103', '2A', 'Exceso de velocidad. Hasta 20 km/h por encima de la velocidad permitida (d.640)', 5.0],
            ['103', '2B', 'Exceso de velocidad. Entre 21 km/h y 30 km/h por encima de la velocidad permitida', 8.0],
            ['103', '2C', 'Exceso de velocidad. Más de 30 km/h por encima de la velocidad permitida', 12.0],
            ['103', '3', 'No reducir la velocidad al aproximarse a cruce (d.640)', 1.5],
            ['104', '', 'Circular a baja velocidad obstruyendo la circulación normal (d.641)', 0.6],
            ['105', 'A', 'No reducir la velocidad en aglomeración de personas, especialmente niños (d.642)', 8.0],
            ['105', 'B', 'No reducir la velocidad en aglomeración de vehículos (d.642)', 1.5],
            ['105', 'C', 'No reducir la velocidad al alcanzar un vehículo de transporte colectivo de pasajeros o escolares debidamente identificados detenido para el ascenso o descenso de pasaje (d.642)', 1.5],
            ['106', '', 'No detener la marcha cuando lo indiquen agentes de tránsito. Cruzar o girar con luz roja (d.643)', 5.0],
            ['107', '', 'Frenar bruscamente sin existir razones que lo ameriten (d.644)', 1.5],
            ['108', '1', 'Detención o estacionamiento generando peligro en la circulación (d.645)', 0.3],
            ['108', '2A', 'Estacionamiento a contramano (d.645)', 4.0],
            ['108', '2B', 'Estacionamiento a más de 30 centímetros del cordón (d.645)', 4.0],
            ['108', '2C', 'Estacionamiento no paralelo al cordón (d.645)', 0.3],
            ['108', '2D', 'Estacionar sin dejar espacio que permita maniobrar a otros vehículos estacionados (d.645)', 0.3],
            ['109', '', 'Salir de detención o estacionamiento sin hacer señales correspondientes o con riesgos para terceros (d.646)', 0.6],
            ['110', '', 'Estacionar en lugar prohibido, reservados o zonas de carga (d.647)', 2.0],
            ['110', 'A', 'Estacionar en zona tarifada sin abonar tarifa (d.647)', 2.0],
            ['110', 'B', 'Estacionar en zona tarifada con plazo vencido d.647)', 1.0],
            ['111', 'A', 'Estacionar en doble fila (d.648)', 5.0],
            ['111', 'B', 'Estacionar en ángulo de dos vías (d.648)', 1.0],
            ['111', 'C', 'Estacionar en cruce peatonal (d.648)', 1.0],
            ['111', 'D', 'Estacionar frente a obras u obstrucción- provocando dificultades al tránsito vehicular o peatonal (d.648)', 0.6],
            ['111', 'E', 'Estacionar en cualquier paso a desnivel (puente o túnel) (d.648)', 1.0],
            ['111', 'F', 'Estacionar en curvas o rasantes de visibilidad reducida (d.648)', 1.0],
            ['111', 'G', 'Estacionar a menos de 10 metros de cartel de pare o ceda el paso (d.648)', 1.0],
            ['111', 'H', 'Estacionar en paradas de taxímetros o transporte colectivo (d.648)', 1.0],
            ['111', 'I', 'Estacionar frente a entrada de garaje (d.648)', 1.0],
            ['111', 'J', 'Estacionar delante de surtidores de combustible (d.648)', 1.0],
            ['111', 'K', 'Estacionar delante de talleres mecánicos para efectuar reparaciones (d.648)', 1.0],
            ['111', 'L', 'Estacionar junto a canteros centrales (d.648)', 3.0],
            ['111', 'M', 'Estacionar frente a salas de espectáculos públicos (d.648)', 0.3],
            ['111', 'N', 'Estacionamiento nocturno en la vía publica dentro de la zona urbana de transporte de pasajeros, cargas o camiones cisternas (d.648)', 1.5],
            ['111', 'P', 'Estacionar en ciclovia o bicisenda', 2.0],
            ['112', '', 'Estacionado con motor encendido sin conductor (d.649)', 0.6],
            ['113', '', 'Abrir puertas sin que el vehículo este detenido o estacionado, o no usar las del lado de la acera sin motivo (650)', 0.3],
            ['114', '', 'Abrir las puertas del lado del tránsito sin motivo o más tiempo del necesario (d.651)', 0.3],
            ['116', '', 'Estacionamiento por más de 48 horas ininterrumpidas (d.653)', 0.6],
            ['117', '', 'Realizar carga y descarga de mercaderías en forma antirreglamentaria (d.654)', 1.0],
            ['118', '', 'Limitaciones dispuestas para operaciones de carga y descarga (d.655)', 0.6],
            ['119', '', 'Estacionar sobre el pavimento en zonas rurales (d.656)', 0.6],
            ['120', '', 'Obstrucción del tránsito (d.657)', 1.0],
            ['123', '', 'No respetar paso a nivel ferroviario (d.660)', 1.5],
            ['124', '', 'Cruzar vía férrea con barreras bajas (d.661)', 1.5],
            ['126', '', 'Uso indebido o con riesgo de las excepciones otorgadas a vehículos en emergencia (d.663)', 1.5],
            ['127', '', 'Uso de sonidos o luces que puedan confundirse con vehículos autorizados de emergencia (d.664)', 1.2],
            ['128', '1', 'Circula con luces apagadas', 1.0],
            ['129', '', 'Falta de luces delanteras reglamentarias (d.666)', 1.5],
            ['130', '', 'Falta de luces traseras reglamentarias (d.667)', 1.5],
            ['131', '', 'Falta de luces encendidas en vehículos estacionados (d.668)', 0.6],
            ['132', '', 'Uso de luces largas al aproximarse un vehículo en sentido contrario (d.669)', 1.0],
            ['133', '', 'Uso de luces largas encandilando a conductor de un vehículo que circula delante (d.670)', 0.6],
            ['134', '', 'Uso de luces direccionales (d.671)', 1.0],
            ['135', '', 'Ómnibus y camiones: no llevar encendidas luces complementarias reglamentarias en las horas exigidas (d.672)', 1.0],
            ['136', '', 'Prohibición de usar faros móviles (buscadores o pilotos) (d.673)', 1.0],
            ['137', '', 'Uso indebido de faros de niebla (d.674)', 1.0],
            ['138', '', 'Prohibición de usar luces rojas por delante o blancas por detrás o aquellas que provoquen confusión a otros conductores (d.675)', 1.0],
            ['139', '', 'Conduce con imprudencia, descuido o desatención a la conducción (d.676)', 1.5],
            ['140', '1B', 'Circular en condiciones antirreglamentarias (d.677)', 1.0],
            ['140', '1C', 'Conducir con exceso de carga (d.677)', 1.0],
            ['140', '1D', 'Conducir vehículos o cargas excedidas de medidas reglamentarias (d.677)', 1.0],
            ['140', '1F', 'Entorpecer columnas de escolares- fuerzas armadas- desfiles autorizados o cortejos fúnebres (d.677)', 1.5],
            ['140', '1G', 'Realizar competencias deportivas sin autorización (d.677)', 1.0],
            ['140', '1H', 'Conducir vehículos en caravana o convoy sin autorización (d.677)', 1.5],
            ['140', '1I', 'Uso indebido de aparato fonético (d.677)', 1.2],
            ['140', '1M', 'Conducir vehículos automotores cuya inscripción haya caducado por adeudar cinco o más años del tributo de Patente de Rodados. (d.677)', 1.0],
            ['140', '2A', 'Vehículo con exceso de humo (d.677)', 1.0],
            ['140', '2B', 'Circular con vehículos que emiten sonidos fuertes o con escape abierto (d.677)', 1.0],
            ['140', '2C', 'Mantener motor en marcha mientras se carga combustible (d.677)', 0.6],
            ['140', '2D', 'Circular junto a tropas de ganado a más de 30 km/h (d.677)', 1.5],
            ['140', '2E', 'Escape libre ruidoso en motos', 10.0],
            ['141', '', 'No portar licencia de conducir, documento de identificación del vehículo o negarse a presentarlas (d.678)', 1.0],
            ['142', '', 'No presentar el vehículo a inspección (d.679)', 2.5],
            ['143', '', 'Circulación de vehículos que lleven máquinas que emanen sustancias nocivas (d.680)', 0.6],
            ['145', '', 'Prohibición de circular sin rodado de goma (d.682)', 1.5],
            ['148', '3', 'No utiliza cinturón de seguridad ( d.685.3)', 1.0],
            ['161', '', 'Conducir el vehículo o llevar acompañante en forma antirreglamentaria (d.698)', 1.5],
            ['162', '', 'No respetar derecho de uso de una senda por motocicleta (d.699)', 1.5],
            ['163', '', 'Alcanzar o rebasar a otro vehículo que circula por la misma senda (d.700)', 1.5],
            ['164', '', 'Prohibición de circular entre dos sendas o entre filas contiguas de vehículos (d.701)', 1.5],
            ['165', '', 'Prohibición de circular más de dos motocicletas en una misma senda (d.702)', 1.5],
            ['167', '', 'Prohibición de sujetarse a otro vehículo (d.704)', 1.5],
            ['168', '', 'Omisión de llevar posapies para el acompañante (d.705)', 0.6],
            ['169', '', 'Motocicleta con manillar a más de 40 centímetros del asiento (d.706)', 0.6],
            ['170', '', 'Circular sin casco (d.707)', 2.0],
            ['171', '', 'Conducir sin llevar los ojos protegidos en motocicleta sin parabrisas (d.708)', 1.5],
            ['172', '', 'Llevar cargas que afecten la estabilidad, visibilidad o contralor del vehículo (d.709)', 1.0]
        ];

        foreach ($infracciones as $infraccion) {
            InfraccionTransito::create([
                'articulo' => $infraccion[0],
                'apartado' => $infraccion[1] ?: null,
                'descripcion' => $infraccion[2],
                'importe_ur' => $infraccion[3],
                'decreto' => isset($infraccion[4]) ? $infraccion[4] : null,
                'activo' => true
            ]);
        }

    }

}
