<?php

namespace Database\Seeders\Tesoreria;

use Illuminate\Database\Seeder;
use App\Models\Tesoreria\Multa;

class MultaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // --- REFACTORIZADO ---
        // El array ahora contiene: [articulo, apartado, descripcion, moneda, importe_original, decreto, importe_unificado]
        // Se ha agregado la moneda a cada registro para mayor flexibilidad.
        $multas = [
            // Multas de Tránsito Generales (UR)
            ['2', null, 'Desobediencia a las disposiciones (d.539)', 'UR', 1.5, null, 3.0],
            ['3', null, 'Desobediencia a señalización (d.540)', 'UR', 1.5, null, 3.0],
            ['4', 'B', 'Vehículo circulando por la acera (d.541)', 'UR', 4.0, null, 3.0],
            ['4', '4/2', 'Conduce usando celular', 'UR', 3.0, 'Decreto Nº 81/014', 3.0],
            ['4', '9/1', 'Menor en asiento delantero', 'UR', 3.0, 'Decreto Nº 81/014', 3.0],
            ['4', '9/2', 'No utiliza sistema de retención infantil', 'UR', 2.0, 'Decreto Nº 81/014', 2.0],
            ['5', 'A', 'Vehículos: uso indebido de las aceras, no dar preferencia al peatón (d.542)', 'UR', 4.0, null, 3.0],
            ['5', 'B', 'Entrada y salida del inmueble cuando el cordón no está dispuesto a esos efectos (d.542)', 'UR', 4.0, null, 2.0],
            ['5', 'C', 'Prohibición de estacionar sobre la acera (d.542)', 'UR', 4.0, null, 2.0],
            ['5', 'D', 'Circula por ciclovía o bicisenda', 'UR', 4.0, null, null],
            ['6', null, 'Peatón uso indebido de la calzada (d.543)', 'UR', 0.1, null, null],
            ['7', null, 'No obedecer limitaciones de circulación temporaria (d.544)', 'UR', 1.0, null, 6.0],
            ['8', '1', 'Conduce sin licencia o con licencia suspendida (d.545)', 'UR', 8.0, null, 15.0],
            ['8', '2', 'Licencia no habilitada para el vehículo que conduce (d.545)', 'UR', 2.5, null, 6.0],
            ['9', '1', 'Conduce sin poseer cualidades físicas o psíquicas que lo habiliten (d.546)', 'UR', 2.5, null, 1.0],
            ['9', '2', 'Persona con discapacidad conduciendo vehículo sin autorización (d.546)', 'UR', 2.5, null, 1.0],
            ['11', '1', 'Aspirante a conductor no autorizado (d.548)', 'UR', 1.0, null, null],
            ['11', '2', 'Instructor no habilitado (d.548)', 'UR', 1.0, null, null],
            ['12', '15A', 'Alcoholemia', 'UR', 15.0, null, 15.0],
            ['12', '15B', 'Presencia de drogas psicotrópicas', 'UR', 15.0, null, 15.0],
            ['14', null, 'Conduce vehículos especiales sin permiso (d.551)', 'UR', 2.5, null, 15.0],
            ['15', null, 'Conduce con licencia sin reválida (d.552)', 'UR', 2.5, null, 6.0],
            ['16', null, 'Omisión de actualización de domicilio (d.553)', 'UR', 0.3, null, 1.0],
            ['17', null, 'Posee más de una licencia de conducir (d.554)', 'UR', 2.5, null, null],
            ['18', null, 'Omisión de entregar licencia anterior al recibir una nueva (d.555)', 'UR', 2.5, null, null],
            ['19', null, 'Conduce con licencia vencida (d.556)', 'UR', 1.0, null, 6.0],
            ['21', null, 'Licencia condicional vencida (d.558)', 'UR', 2.5, null, 6.0],
            ['21', '7', 'Niños y adolescentes no alcanzan los posapies en motos', 'UR', 1.0, 'Decreto Nº 81/014', 1.0],
            ['21', '8', 'No usa chaleco o bandas retro reflectivas reglamentarias', 'UR', 0.5, 'Decreto Nº 81/014', 0.5],
            ['22', null, 'Circulación de vehículo sin empadronar (d.559)', 'UR', 2.5, null, 6.0],
            ['22', '4', 'Prohibido el transporte de personas en la caja de vehículos', 'UR', 4.0, 'Decreto Nº 81/014', 2.0],
            ['28', null, 'Circula con vehículo no inspeccionado (d.565)', 'UR', 1.0, null, 2.0],
            ['30', null, 'Vehículo con exceso de peso sobre el pavimento (d.567)', 'UR', 5.0, null, 8.0],
            ['33', null, 'Omisión de comunicar fallecimiento del propietario de un vehículo (d.570)', 'UR', 0.3, null, 3.0],
            ['34', null, 'Circula sin placas de matrícula (d.571)', 'UR', 1.0, null, 4.0],
            ['35', null, 'Circula con placas deterioradas o ubicadas en lugar no visible (d.572)', 'UR', 1.0, null, 2.0],
            ['36', null, 'Circula sin matrícula por extravío- sustracción o deterioro (d.573)', 'UR', 1.0, null, 4.0],
            ['37', null, 'Circula con matrículas no vigentes (d.574)', 'UR', 1.0, null, 6.0],
            ['39', null, 'Circula con placas no originales (d.576)', 'UR', 1.0, null, 4.0],
            ['40', null, 'Mal uso de placas de prueba (d.577)', 'UR', 1.5, null, null],
            ['41', null, 'Circula con placas de prueba de otro departamento sin el permiso correspondiente (d.578)', 'UR', 1.5, null, null],
            ['43', null, 'Mal uso de placas de demostración de usado y de prueba (d.580)', 'UR', 1.5, null, null],
            ['44', null, 'No realiza transferencia (d.581)', 'UR', 1.0, null, 3.0],
            ['47', null, 'Omisión de devolver placas de matrículas beneficiarias de privilegios (d.584)', 'UR', 1.0, null, null],
            ['60', null, 'Obligación de evitar accidentes ante inobservancia de peatones- especialmente de niños o personas con discapacidad (d.597)', 'UR', 1.5, null, 4.0],
            ['61', null, 'No circula por derecha. adelanta en una intersección o adelanta varios vehículos a la vez (d.598)', 'UR', 1.0, null, 3.0],
            ['62', null, 'No conserva la derecha cuando se circula a velocidad reducida (d.599)', 'UR', 1.0, null, 3.0],
            ['63', null, 'No conserva la derecha en rebase de vehículos con sentidos opuestos o no cede el paso a quien circula por la mitad más transitada (d.600)', 'UR', 1.0, null, 3.0],
            ['64', null, 'Circula por izquierda de la calzada con visual limitada (curvas- puentes- declives) (d.601)', 'UR', 1.0, null, 3.0],
            ['65', null, 'Circula en sentido contrario (d.602)', 'UR', 1.0, null, 4.0],
            ['66', null, 'No circular por la derecha alrededor del "rond point" (d.603)', 'UR', 1.0, null, 4.0],
            ['67', null, 'No se mantiene dentro de una senda o abandona con riesgo carriles de circulación (d.604)', 'UR', 1.0, null, 2.0],
            ['68', null, 'Circular por la mitad izquierda en calzadas de doble mano que dispongan de cuatro o más sendas de circulación (d. 605)', 'UR', 1.0, null, 3.0],
            ['69', null, 'No ceder el paso a vehículo que circula en sentido contrario al enfrentar obstáculo (d.606)', 'UR', 1.0, null, 3.0],
            ['70', 'A', 'Adelantar por derecha (d.607)', 'UR', 0.6, null, 3.0],
            ['70', 'B', 'Retomar la línea de marcha antes de encontrarse a distancia segura del rebasado (d.607)', 'UR', 0.6, null, 3.0],
            ['70', 'C', 'Aumentar la velocidad mientras otro vehículo está adelantando (d.607)', 'UR', 0.6, null, 3.0],
            ['70', 'D', 'Adelantar en intersección (d.607)', 'UR', 0.6, null, 4.0],
            ['70', 'E', 'Adelantar por izquierda a quien gira a la izquierda (d.607)', 'UR', 0.6, null, 3.0],
            ['71', null, 'Adelantar cuando otro vehículo inicia igual maniobra (d.608)', 'UR', 0.6, null, 3.0],
            ['72', null, 'Adelantar o rebasar obstáculos en calles de doble sentido invadiendo senda izquierda con riesgo para peatones o vehículos (d.610)', 'UR', 0.6, null, 3.0],
            ['73', null, 'Rebasar vehículo que disminuye la velocidad o se detiene en cruce peatonal- o no detenerse junto a ómnibus detenido en la parada adelantándolo sin precaución (d.610)', 'UR', 0.6, null, 4.0],
            ['75', null, 'No respetar prohibición de adelantamientos (d.612)', 'UR', 1.0, null, 3.0],
            ['76', null, 'No conservar una distancia razonable y prudente en la circulación (d.613)', 'UR', 1.5, null, 4.0],
            ['77', null, 'Seguir vehículos de emergencia a menos de 100 metros (d.614)', 'UR', 1.5, null, 4.0],
            ['78', null, 'Circulación de vehículos especiales o con cargas excesivas, desagradables o peligrosas sin autorización (d.615)', 'UR', 1.0, null, 15.0],
            ['79', null, 'Conducir un vehículo cuando está cargado de tal modo por bultos o personas que se obstaculiza la buena visión del conductor o que estorba el control del vehículo (d.616)', 'UR', 1.0, null, 4.0],
            ['80', null, 'Prohibición de remolcar vehículos (d.617)', 'UR', 1.0, null, 3.0],
            ['81', null, 'Marcha atrás innecesaria (d.618)', 'UR', 0.5, null, 3.0],
            ['82', null, 'En pendientes descendentes no controlar la velocidad con motor (d.619)', 'UR', 1.5, null, null],
            ['85', 'A', 'No respetar cartel de pare (d.622)', 'UR', 3.0, null, 6.0],
            ['85', 'B', 'No respetar cartel de ceda el paso (d.622)', 'UR', 3.0, null, 6.0],
            ['87', '1', 'No ceder el paso al vehículo que aparece por la derecha (d.624)', 'UR', 1.0, null, 4.0],
            ['87', '2', 'No reducir la velocidad en intersecciones de calles no preferenciales (d.624)', 'UR', 1.0, null, 4.0],
            ['88', null, 'Desobediencia al funcionario que dirige tránsito (d.625)', 'UR', 5.0, null, 6.0],
            ['89', 'A', 'Vehículo que cambia de dirección o sentido de marcha no da preferencia (d.626)', 'UR', 1.0, null, 4.0],
            ['89', 'B', 'Vehículo que cambia de frente para salir de inmueble no da preferencia (d.626)', 'UR', 1.0, null, 4.0],
            ['90', null, 'No dar preferencia a peatones (d.627)', 'UR', 1.0, null, 4.0],
            ['92', null, 'No dar preferencia a peatones que transiten por la acera - al entrar o salir de pasaje- edificio o calzada particular (d.629)', 'UR', 1.0, null, 4.0],
            ['93', null, 'No ceder el paso o no ubicarse a la derecha de la calzada ante el pasaje de vehículo autorizado de emergencia usando señales reglamentarias (d.630)', 'UR', 2.5, null, 6.0],
            ['94', null, 'No ubicarse correctamente para girar a la derecha o girar en doble fila a la derecha (d.631)', 'UR', 1.0, null, 3.0],
            ['95', null, 'No ubicarse correctamente para girar a la izquierda o girar en doble fila a la izquierda (d.632)', 'UR', 1.0, null, 2.0],
            ['96', null, 'Salir o ingresar de garaje o pasaje privado por izquierda en calles de doble sentido de circulación (d.633)', 'UR', 1.0, null, null],
            ['97', null, 'Cambio de frente prohibido (d.634)', 'UR', 1.0, null, 4.0],
            ['98', null, 'Giro en lugar prohibido (d.635)', 'UR', 1.0, null, 4.0],
            ['99', null, 'Desplazar vehículo fuera de su curso recto sin seguridad o sin realizar las señales correspondientes en maniobra de giro (d.636)', 'UR', 1.0, null, 3.0],
            ['100', null, 'No realizar señales adecuadas para reducir la marcha o detenerse (d.637)', 'UR', 0.6, null, 3.0],
            ['101', 'A', 'No indicar giro a la izquierda (d.638)', 'UR', 1.0, null, 2.0],
            ['101', 'B', 'No indicar giro a la derecha (d.638)', 'UR', 1.0, null, 3.0],
            ['101', 'C', 'No indicar reducción de velocidad (d.638)', 'UR', 0.6, null, 3.0],
            ['102', null, 'Hacer señales de giro o detención y no realizar maniobra (d.639)', 'UR', 0.6, null, 3.0],
            ['103', '1', 'Imprudencia o desatención en el manejo (d.640)', 'UR', 1.5, null, 4.0],
            ['103', '2A', 'Exceso de velocidad. Hasta 20 km/h por encima de la velocidad permitida (d.640)', 'UR', 5.0, null, 5.0],
            ['103', '2B', 'Exceso de velocidad. Entre 21 km/h y 30 km/h por encima de la velocidad permitida', 'UR', 8.0, null, 8.0],
            ['103', '2C', 'Exceso de velocidad. Más de 30 km/h por encima de la velocidad permitida', 'UR', 12.0, null, 12.0],
            ['103', '3', 'No reducir la velocidad al aproximarse a cruce (d.640)', 'UR', 1.5, null, 4.0],
            ['104', null, 'Circular a baja velocidad obstruyendo la circulación normal (d.641)', 'UR', 0.6, null, 2.0],
            ['105', 'A', 'No reducir la velocidad en aglomeración de personas, especialmente niños (d.642)', 'UR', 8.0, null, 4.0],
            ['105', 'B', 'No reducir la velocidad en aglomeración de vehículos (d.642)', 'UR', 1.5, null, 4.0],
            ['105', 'C', 'No reducir la velocidad al alcanzar un vehículo de transporte colectivo de pasajeros o escolares debidamente identificados detenido para el ascenso o descenso de pasaje (d.642)', 'UR', 1.5, null, 4.0],
            ['106', null, 'No detener la marcha cuando lo indiquen agentes de tránsito. Cruzar o girar con luz roja (d.643)', 'UR', 5.0, null, 6.0],
            ['107', null, 'Frenar bruscamente sin existir razones que lo ameriten (d.644)', 'UR', 1.5, null, 3.0],
            ['108', '1', 'Detención o estacionamiento generando peligro en la circulación (d.645)', 'UR', 0.3, null, 2.0],
            ['108', '2A', 'Estacionamiento a contramano (d.645)', 'UR', 4.0, null, 3.0],
            ['108', '2B', 'Estacionamiento a más de 30 centímetros del cordón (d.645)', 'UR', 4.0, null, 2.0],
            ['108', '2C', 'Estacionamiento no paralelo al cordón (d.645)', 'UR', 0.3, null, 2.0],
            ['108', '2D', 'Estacionar sin dejar espacio que permita maniobrar a otros vehículos estacionados (d.645)', 'UR', 0.3, null, 2.0],
            ['109', null, 'Salir de detención o estacionamiento sin hacer señales correspondientes o con riesgos para terceros (d.646)', 'UR', 0.6, null, 3.0],
            ['110', null, 'Estacionar en lugar prohibido, reservados o zonas de carga (d.647)', 'UR', 2.0, null, 2.0],
            ['110', 'A', 'Estacionar en zona tarifada sin abonar tarifa (d.647)', 'UR', 2.0, null, 2.0],
            ['110', 'B', 'Estacionar en zona tarifada con plazo vencido d.647)', 'UR', 1.0, null, 1.0],
            ['111', 'A', 'Estacionar en doble fila (d.648)', 'UR', 5.0, null, 3.0],
            ['111', 'B', 'Estacionar en ángulo de dos vías (d.648)', 'UR', 1.0, null, 2.0],
            ['111', 'C', 'Estacionar en cruce peatonal (d.648)', 'UR', 1.0, null, 3.0],
            ['111', 'D', 'Estacionar frente a obras u obstrucción- provocando dificultades al tránsito vehicular o peatonal (d.648)', 'UR', 0.6, null, 3.0],
            ['111', 'E', 'Estacionar en cualquier paso a desnivel (puente o túnel) (d.648)', 'UR', 1.0, null, 8.0],
            ['111', 'F', 'Estacionar en curvas o rasantes de visibilidad reducida (d.648)', 'UR', 1.0, null, 8.0],
            ['111', 'G', 'Estacionar a menos de 10 metros de cartel de pare o ceda el paso (d.648)', 'UR', 1.0, null, 2.0],
            ['111', 'H', 'Estacionar en paradas de taxímetros o transporte colectivo (d.648)', 'UR', 1.0, null, 3.0],
            ['111', 'I', 'Estacionar frente a entrada de garaje (d.648)', 'UR', 1.0, null, 2.0],
            ['111', 'J', 'Estacionar delante de surtidores de combustible (d.648)', 'UR', 1.0, null, 2.0],
            ['111', 'K', 'Estacionar delante de talleres mecánicos para efectuar reparaciones (d.648)', 'UR', 1.0, null, 2.0],
            ['111', 'L', 'Estacionar junto a canteros centrales (d.648)', 'UR', 3.0, null, 3.0],
            ['111', 'M', 'Estacionar frente a salas de espectáculos públicos (d.648)', 'UR', 0.3, null, 2.0],
            ['111', 'N', 'Estacionamiento nocturno en la vía publica dentro de la zona urbana de transporte de pasajeros, cargas o camiones cisternas (d.648)', 'UR', 1.5, null, 2.0],
            ['111', 'P', 'Estacionar en ciclovia o bicisenda', 'UR', 2.0, null, null],
            ['112', null, 'Estacionado con motor encendido sin conductor (d.649)', 'UR', 0.6, null, 3.0],
            ['113', null, 'Abrir puertas sin que el vehículo este detenido o estacionado, o no usar las del lado de la acera sin motivo (650)', 'UR', 0.3, null, 2.0],
            ['114', null, 'Abrir las puertas del lado del tránsito sin motivo o más tiempo del necesario (d.651)', 'UR', 0.3, null, 2.0],
            ['116', null, 'Estacionamiento por más de 48 horas ininterrumpidas (d.653)', 'UR', 0.6, null, 2.0],
            ['117', null, 'Realizar carga y descarga de mercaderías en forma antirreglamentaria (d.654)', 'UR', 1.0, null, 3.0],
            ['118', null, 'Limitaciones dispuestas para operaciones de carga y descarga (d.655)', 'UR', 0.6, null, 3.0],
            ['119', null, 'Estacionar sobre el pavimento en zonas rurales (d.656)', 'UR', 0.6, null, 3.0],
            ['120', null, 'Obstrucción del tránsito (d.657)', 'UR', 1.0, null, 3.0],
            ['123', null, 'No respetar paso a nivel ferroviario (d.660)', 'UR', 1.5, null, 6.0],
            ['124', null, 'Cruzar vía férrea con barreras bajas (d.661)', 'UR', 1.5, null, 6.0],
            ['126', null, 'Uso indebido o con riesgo de las excepciones otorgadas a vehículos en emergencia (d.663)', 'UR', 1.5, null, 6.0],
            ['127', null, 'Uso de sonidos o luces que puedan confundirse con vehículos autorizados de emergencia (d.664)', 'UR', 1.2, null, 2.0],
            ['128', '1', 'Circula con luces apagadas', 'UR', 1.0, null, 4.0],
            ['129', null, 'Falta de luces delanteras reglamentarias (d.666)', 'UR', 1.5, null, 4.0],
            ['130', null, 'Falta de luces traseras reglamentarias (d.667)', 'UR', 1.5, null, 3.0],
            ['131', null, 'Falta de luces encendidas en vehículos estacionados (d.668)', 'UR', 0.6, null, 2.0],
            ['132', null, 'Uso de luces largas al aproximarse un vehículo en sentido contrario (d.669)', 'UR', 1.0, null, 3.0],
            ['133', null, 'Uso de luces largas encandilando a conductor de un vehículo que circula delante (d.670)', 'UR', 0.6, null, 3.0],
            ['134', null, 'Uso de luces direccionales (d.671)', 'UR', 1.0, null, 2.0],
            ['135', null, 'Ómnibus y camiones: no llevar encendidas luces complementarias reglamentarias en las horas exigidas (d.672)', 'UR', 1.0, null, 2.0],
            ['136', null, 'Prohibición de usar faros móviles (buscadores o pilotos) (d.673)', 'UR', 1.0, null, 2.0],
            ['137', null, 'Uso indebido de faros de niebla (d.674)', 'UR', 1.0, null, 2.0],
            ['138', null, 'Prohibición de usar luces rojas por delante o blancas por detrás o aquellas que provoquen confusión a otros conductores (d.675)', 'UR', 1.0, null, 2.0],
            ['139', null, 'Conduce con imprudencia, descuido o desatención a la conducción (d.676)', 'UR', 1.5, null, 4.0],
            ['140', '1B', 'Circular en condiciones antirreglamentarias (d.677)', 'UR', 1.0, null, 4.0],
            ['140', '1C', 'Conducir con exceso de carga (d.677)', 'UR', 1.0, null, 8.0],
            ['140', '1D', 'Conducir vehículos o cargas excedidas de medidas reglamentarias (d.677)', 'UR', 1.0, null, 8.0],
            ['140', '1F', 'Entorpecer columnas de escolares- fuerzas armadas- desfiles autorizados o cortejos fúnebres (d.677)', 'UR', 1.5, null, null],
            ['140', '1G', 'Realizar competencias deportivas sin autorización (d.677)', 'UR', 1.0, null, 15.0],
            ['140', '1H', 'Conducir vehículos en caravana o convoy sin autorización (d.677)', 'UR', 1.5, null, 4.0],
            ['140', '1I', 'Uso indebido de aparato fonético (d.677)', 'UR', 1.2, null, 5.0],
            ['140', '1M', 'Conducir vehículos automotores cuya inscripción haya caducado por adeudar cinco o más años del tributo de Patente de Rodados. (d.677)', 'UR', 1.0, null, 6.0],
            ['140', '2A', 'Vehículo con exceso de humo (d.677)', 'UR', 1.0, null, 4.0],
            ['140', '2B', 'Circular con vehículos que emiten sonidos fuertes o con escape abierto (d.677)', 'UR', 1.0, null, 4.0],
            ['140', '2C', 'Mantener motor en marcha mientras se carga combustible (d.677)', 'UR', 0.6, null, 3.0],
            ['140', '2D', 'Circular junto a tropas de ganado a más de 30 km/h (d.677)', 'UR', 1.5, null, 2.0],
            ['140', '2E', 'Escape libre ruidoso en motos', 'UR', 10.0, null, 5.0],
            ['141', null, 'No portar licencia de conducir, documento de identificación del vehículo o negarse a presentarlas (d.678)', 'UR', 1.0, null, 6.0],
            ['142', null, 'No presentar el vehículo a inspección (d.679)', 'UR', 2.5, null, 2.0],
            ['143', null, 'Circulación de vehículos que lleven máquinas que emanen sustancias nocivas (d.680)', 'UR', 0.6, null, 4.0],
            ['145', null, 'Prohibición de circular sin rodado de goma (d.682)', 'UR', 1.5, null, 2.0],
            ['148', '3', 'No utiliza cinturón de seguridad ( d.685.3)', 'UR', 1.0, null, 2.0],
            ['161', null, 'Conducir el vehículo o llevar acompañante en forma antirreglamentaria (d.698)', 'UR', 1.5, null, 4.0],
            ['162', null, 'No respetar derecho de uso de una senda por motocicleta (d.699)', 'UR', 1.5, null, 2.0],
            ['163', null, 'Alcanzar o rebasar a otro vehículo que circula por la misma senda (d.700)', 'UR', 1.5, null, 2.0],
            ['164', null, 'Prohibición de circular entre dos sendas o entre filas contiguas de vehículos (d.701)', 'UR', 1.5, null, 4.0],
            ['165', null, 'Prohibición de circular más de dos motocicletas en una misma senda (d.702)', 'UR', 1.5, null, 4.0],
            ['167', null, 'Prohibición de sujetarse a otro vehículo (d.704)', 'UR', 1.5, null, 4.0],
            ['168', null, 'Omisión de llevar posapies para el acompañante (d.705)', 'UR', 0.6, null, 1.0],
            ['169', null, 'Motocicleta con manillar a más de 40 centímetros del asiento (d.706)', 'UR', 0.6, null, 4.0],
            ['170', null, 'Circular sin casco (d.707)', 'UR', 2.0, null, 1.0],
            ['171', null, 'Conducir sin llevar los ojos protegidos en motocicleta sin parabrisas (d.708)', 'UR', 1.5, null, 1.0],
            ['172', null, 'Llevar cargas que afecten la estabilidad, visibilidad o contralor del vehículo (d.709)', 'UR', 1.0, null, 2.0],

            // Multas por Falta de SOA (UYU)
            ['184', '1', 'Carecer de SOA: Motos', 'UYU', 5154.00, null, null],
            ['184', '2', 'Carecer de SOA: Automóviles y Camionetas', 'UYU', 13066.00, null, null],
            ['184', '3', 'Carecer de SOA: Camiones', 'UYU', 22498.00, null, null],
            ['184', '4', 'Carecer de SOA: Omnibus', 'UYU', 26328.00, null, null],
            ['184', '5', 'Carecer de SOA: Taxis', 'UYU', 15402.00, null, null],
            ['184', '6', 'Carecer de SOA: Remises', 'UYU', 14074.00, null, null],
            ['184', '7', 'Carecer de SOA: Vehículos de alq sin chofer', 'UYU', 14846.00, null, null],
            ['184', '8', 'Carecer de SOA: Ambulancias', 'UYU', 14166.00, null, null],
            ['184', '9', 'Carecer de SOA: Coche Escuela', 'UYU', 13600.00, null, null],
            ['184', '10', 'Carecer de SOA: Trailers', 'UYU', 10290.00, null, null],
            ['184', '11', 'Carecer de SOA: Casa Rodante', 'UYU', 27118.00, null, null],
            ['184', '12', 'Carecer de SOA: Tractores, semi remolques', 'UYU', 14056.00, null, null],
            ['184', '13', 'Carecer de SOA: Otros', 'UYU', 19366.00, null, null],
        ];

        foreach ($multas as $multa) {
            Multa::create([
                'articulo' => $multa[0],
                'apartado' => $multa[1],
                'descripcion' => $multa[2],
                'moneda' => $multa[3],
                'importe_original' => $multa[4],
                'decreto' => $multa[5],
                'importe_unificado' => $multa[6],
            ]);
        }
    }
}
